---
- name: Install packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - python3-pip

- name: Add docker gpg key
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Configure docker repository
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
    https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install the docker python library
  shell: pip3 install docker

- name: Upgrade packages
  apt:
    upgrade: "yes"
    update_cache: "yes"

- name: Install docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Start docker
  command: echo "starting docker"
  notify: "start docker"
